# Generated by Django 3.2.9 on 2021-12-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('path', models.TextField()),
                ('_is_public', models.BooleanField(default=False)),
            ],
        ),
    ]
