# Generated by Django 4.0.2 on 2022-10-09 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TCFrontEnd', '0002_product_pipeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='creation_priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='filename_patern',
            field=models.TextField(default=None, null=True),
        ),
    ]
