# Generated by Django 3.2.9 on 2021-12-14 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('url_path', models.TextField()),
                ('username', models.CharField(default=None, max_length=64, null=True)),
                ('password', models.CharField(default=None, max_length=64, null=True)),
                ('description', models.TextField()),
                ('is_local', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('path', models.TextField()),
                ('filename', models.TextField()),
                ('description', models.TextField()),
                ('local_path', models.TextField()),
                ('pipeline', models.TextField()),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TCDataCollection.source')),
            ],
        ),
    ]
