# Generated by Django 4.0.2 on 2022-05-23 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TCDataCollection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='pipeline',
        ),
    ]
