# Generated by Django 4.0.2 on 2022-05-25 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TCDataProcessing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storm',
            name='season_number',
            field=models.IntegerField(default=22),
            preserve_default=False,
        ),
    ]
