function [locFiles, locFormat] = GetAELocFiles(varargin)

    wwlln_data_path__ = evalin('caller', 'wwlln_data_path__');
    AEFilesDirectory = fullfile(wwlln_data_path__, 'AEFiles');

    namePattern = [varargin{:}, '*.loc'];

    filename = fullfile(AEFilesDirectory, ['AE', namePattern]);
    locFiles = dir(filename);
    locFormat = struct('formatString',                             ...
                       '%g/%g/%g,%g:%g:%g,%g,%g,%g,%g,%g,%g,%g\n', ...
                       'inputCount', 13,                           ...
                       'indexYr',     1,                           ...
                       'indexMonth',  2,                           ...
                       'indexDay',    3,                           ...
                       'indexHr',     4,                           ...
                       'indexMin',    5,                           ...
                       'indexSec',    6,                           ...
                       'indexLat',    7,                           ...
                       'indexLon',    8);

    % Check for the AE file for the StormDay
    if (size(locFiles, 1) == 0)
        % Check for the A files for the StormDay
        disp(['Could not find file(s): ', filename]);
    end
